version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: employeedb
    networks:
      spring-boot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    image: csclassesnikhil/nikhil-mysql-app:v2
    ports:
      - "9091:9091"
    depends_on:
      - mysqldb
    networks:
      spring-boot-mysql-net:
    restart: on-failure

networks:
  spring-boot-mysql-net: