apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    first: srivastava
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 8081
      targetPort: 8081
  type: LoadBalancer        