apiVersion: v1
kind: Service
metadata:
  name: story-service
  labels:
    first: srivastava
spec:
  selector:
    app: story
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000
  type: LoadBalancer        